[package]
name = "ff_structure"
version = "0.4.0"
description = "fuzzyfold's secondary structure representations."
documentation = "https://docs.rs/ff_structure"
keywords = ["dna", "rna", "secondary-structure"]
readme = "../../README.md"

edition.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true

[dependencies]
nohash-hasher.workspace = true
clap = { version = "4.5.56", features = ["derive"] }
plotters = { version = "0.3", default-features = false, features = ["svg_backend", "line_series", "full_palette"] }



[badges]
maintenance = { status = "actively-developed" }


[[bin]]
name = "ff-arc-diagram"
path = "src/bin/ff-arc-diagram.rs"