use crate::utils::{Move, Intermediate, PathStats, PathStep, compare_structures};
use ff_energy::{NucleotideVec, ViennaRNA, EnergyModel};
use ff_structure::{PairTable, LoopTable, LoopInfo, DotBracketVec};
use crate::greedy::{NeighborCandidate, apply_move, generate_valid_neighbors};



//NOTE: the apply_move function in greedy.rs is implemented to have a maximum energy barrier parameter, which is used in findpath but not in the greedy algorithm.

/// findpath functions.
/// It takes a ViennaRNA energy model, a sequence, a start structure, a target structure, and a maximum energy barrier. It returns a folding path (as a vector of PathStep) and some statistics about the path (as PathStats).
/// The search-with parameter m is used to increase the search space by allowing the m best neighbors (in terms of energy) to be considered at each step, instead of just the single best neighbor (i.e m=1 is equivalent to the greedy algorithm). 
/// This can help to find better paths that might be missed by a purely greedy approach, at the cost of increased computational time.
/// The search space is explored using a breath-first-search approach, where the search-with parameter is doubled at each iteration to allow for wider search.
/// Also the search is performed from both directions (s1 to s2 and s2 to s1), alternating after each applied move.
/// The maximum energy barrier (max_energy) is used to stop the search if the energy of a structure exceeds this value.
pub fn findpath(
    model: &ViennaRNA,
    sequence: &str,
    s1: &str,
    s2: &str,
    m: u16,
    max_energy: Option<f64>,
) -> Result<(Vec<PathStep>, PathStats), String> {

    // 1. Setup & Validation
    let seq_vec = NucleotideVec::from_lossy(sequence);
    let pt_start = PairTable::try_from(s1).map_err(|_| "Invalid start structure s1")?;
    let pt_target = PairTable::try_from(s2).map_err(|_| "Invalid target structure s2")?;

    // 2. Prepare Moves (fwd and bwd moves are the same, but the direction of application is different)
    // therefore, simply change the is_insertion flag for the backward moves
    let comparison = compare_structures(&pt_start, &pt_target);
    let moves_fwd = comparison.move_list;
    let total_steps = moves_fwd.len();

    let moves_bwd: Vec<Move> = moves_fwd.iter().map(|m| Move {
        i: m.i,
        j: m.j,
        is_insertion: !m.is_insertion,
    }).collect();

    // 3. Initialize Energies
    let start_energy = model.energy_of_structure(&seq_vec, &pt_start) as f64 / 100.0;



    // loop: - run_single_beam_pass for forward and backward search, alternating after each applied move
    //       - increase the search width (m) at each iteration (e.g. double m at each iteration)
    //       - stop when a path is found that connects the forward and backward search, or when the maximum energy barrier is exceeded, or when the search space is exhausted (i.e. no more neighbors to explore).
    
    todo!()

}

/// The run_single_beam_pass function performs a single pass of the beam search algorithm. 
/// It takes the current intermediate state, the energy model, the sequence, the target structure, the search width (m), and the maximum energy barrier as input. 
/// It returns a vector of new intermediate states that are generated by applying valid moves to the current state, sorted by their saddle energy (the maximum energy encountered along the path to reach that state). 
/// The function generates valid neighbors by applying moves from the remaining moves list, calculates their energies, and filters them based on the maximum energy barrier. 
/// The resulting neighbors are then sorted and returned for further exploration in the beam search.
fn run_single_beam_pass(
    model: &ViennaRNA,
    sequence: &str,
    s1: &str,
    s2: &str,
    m: u16,
    max_energy: Option<f64>,
) -> Vec<Intermediate> {
    // This function will be called in a loop, alternating between forward and backward search, and increasing the search width (m) at each iteration.
    // The implementation will involve generating valid neighbors for the current intermediate states, applying moves, calculating energies, and filtering based on the maximum energy barrier.
    // The resulting neighbors will be sorted by their saddle energy and returned for further exploration in the beam search.
    
    todo!() // Placeholder 
    // generate_valid_neighbors() -> Vec<NeighborCandidate>
    // apply_move() -> PathStep (with energy calculation)
    // keep m best neighbors based on saddle energy
}