use crate::utils::{Move, Intermediate, PathStats, PathStep, compare_structures};
use ff_energy::{NucleotideVec, ViennaRNA, EnergyModel};
use ff_structure::{PairTable, DotBracketVec};
use crate::greedy::{apply_move};
use std::cmp::Ordering;


//NOTE: the apply_move function in greedy.rs is implemented to have a maximum energy barrier parameter, which is used in findpath but not in the greedy algorithm.

/// findpath functions.
/// It takes a ViennaRNA energy model, a sequence, a start structure, a target structure, and a maximum energy barrier. It returns a folding path (as a vector of PathStep) and some statistics about the path (as PathStats).
/// The search-with parameter m is used to increase the search space by allowing the m best neighbors (in terms of energy) to be considered at each step, instead of just the single best neighbor (i.e m=1 is equivalent to the greedy algorithm). 
/// This can help to find better paths that might be missed by a purely greedy approach, at the cost of increased computational time.
/// The search space is explored using a breath-first-search approach, where the search-with parameter is doubled at each iteration to allow for wider search.
/// Also the search is performed from both directions (s1 to s2 and s2 to s1), alternating after each applied move.
/// The maximum energy barrier (max_energy) is used to stop the search if the energy of a structure exceeds this value.
pub fn _findpath(
    model: &ViennaRNA,
    sequence: &str,
    s1: &str,
    s2: &str,
    m: u16,
    max_energy: Option<f64>,
) -> Result<(Vec<PathStep>, PathStats), String> {

    // 1. Setup & Validation
    let seq_vec = NucleotideVec::from_lossy(sequence);
    let pt_start = PairTable::try_from(s1).map_err(|_| "Invalid start structure s1")?;
    let pt_target = PairTable::try_from(s2).map_err(|_| "Invalid target structure s2")?;

    // 2. Prepare Moves (fwd and bwd moves are the same, but the direction of application is different)
    // therefore, simply change the is_insertion flag for the backward moves
    let comparison = compare_structures(&pt_start, &pt_target);
    let moves_fwd = comparison.move_list;
    let total_steps = moves_fwd.len();

    let moves_bwd: Vec<Move> = moves_fwd.iter().map(|m| Move {
        i: m.i,
        j: m.j,
        is_insertion: !m.is_insertion,
    }).collect();

    // 3. Initialize Energies
    let start_energy = model.energy_of_structure(&seq_vec, &pt_start) as f64 / 100.0;



    // loop: - run_single_beam_pass for forward and backward search, alternating after each applied move
    //       - increase the search width (m) at each iteration (e.g. double m at each iteration)
    //       - stop when a path is found that connects the forward and backward search, or when the maximum energy barrier is exceeded, or when the search space is exhausted (i.e. no more neighbors to explore).
    
    todo!()

}

/// The run_single_beam_pass function performs a single pass of the beam search algorithm. 
/// It takes the current intermediate state, the energy model, the sequence, the target structure, the search width (m), and the maximum energy barrier as input. 
/// It returns a vector of new intermediate states that are generated by applying valid moves to the current state, sorted by their saddle energy (the maximum energy encountered along the path to reach that state). 
/// The function generates valid neighbors by applying moves from the remaining moves list, calculates their energies, and filters them based on the maximum energy barrier. 
/// The resulting neighbors are then sorted and returned for further exploration in the beam search.
fn _run_single_beam_pass(
    model: &ViennaRNA,
    sequence: &str,
    s1: &str,
    s2: &str,
    m: u16,
    max_energy: Option<f64>,
) -> Vec<Intermediate> {
    // This function will be called in a loop, alternating between forward and backward search, and increasing the search width (m) at each iteration.
    // The implementation will involve generating valid neighbors for the current intermediate states, applying moves, calculating energies, and filtering based on the maximum energy barrier.
    // The resulting neighbors will be sorted by their saddle energy and returned for further exploration in the beam search.
    
    todo!() // Placeholder 
    // generate_valid_neighbors() -> Vec<NeighborCandidate>
    // apply_move() -> PathStep (with energy calculation)
    // keep m best neighbors based on saddle energy
}




/// Heuristic findpath strategy with optimized bidirectional beam search.
/// Accepts an optional 'max_energy' parameter to bound the absolute maximum 
/// energy allowed during the search.
pub fn findpath(
    model: &ViennaRNA,
    sequence: &str,
    s1: &str,
    s2: &str,
    target_m: usize,
    mut max_energy: Option<f64>, 
) -> Result<(Vec<PathStep>, PathStats), String> {
    
    // 1. Setup & Pre-calculation (Done ONCE)
    let seq_vec = NucleotideVec::from_lossy(sequence);
    
    let pt_start = PairTable::try_from(s1).map_err(|_| "Invalid start structure s1")?;
    let pt_target = PairTable::try_from(s2).map_err(|_| "Invalid target structure s2")?;

    // Calculate Moves ONCE (Forward: s1 -> s2)
    let fwd_comp = compare_structures(&pt_start, &pt_target);
    let moves_fwd = fwd_comp.move_list;

    // Derive Backward Moves (s2 -> s1) by inverting the insertion logic
    let moves_bwd: Vec<Move> = moves_fwd.iter().map(|m| Move {
        i: m.i,
        j: m.j,
        is_insertion: !m.is_insertion,
    }).collect();

    // 2. State Variables
    let mut current_m: usize = 1;
    let mut forward_dir = true; // True = s1->s2, False = s2->s1
    let mut last_result: Option<(Vec<PathStep>, PathStats)> = None;

    // 3. Iterative Loop
    loop {
        // A. Select Inputs based on Direction
        let (current_pt, current_moves) = if forward_dir {
            (&pt_start, &moves_fwd)
        } else {
            (&pt_target, &moves_bwd)
        };

        // B. Run the Direction-Agnostic Pass
        let pass_result = run_beam_pass(
            model, 
            &seq_vec, 
            current_pt, 
            current_moves, 
            current_m, 
            max_energy
        );

        match pass_result {
            Ok((path, stats)) => {
                // Success: tighten the energy constraint for the next pass
                // We overwrite max_energy with the saddle found so far.
                // This forces the next pass to find a path that is AT LEAST as good.
                max_energy = Some(stats.saddle_energy);
                last_result = Some((path, stats));
            },
            // Err(e) => {
            //     // If it fails on m=1, it means no path exists beneath the initial max_energy
            //     return Err(format!("Pass m={} (direction={}) failed: {}", current_m, forward_dir, e));
            // }

            Err(_e) => {
                // We simply ignore the error.
                // If this pass got stuck due to the energy constraint or topology, 
                // we just let the loop continue to the next width (m) and direction.
                // The last successful result remains safely stored in `last_result`.
            }
        }

        // C. Check Exit Condition
        if current_m == target_m {
            break;
        }

        // D. Prepare Next Iteration
        // Double m, clamp to target_m
        let next_m = current_m * 2;
        current_m = if next_m > target_m { target_m } else { next_m };

        // Flip Direction
        forward_dir = !forward_dir;
    }

    // 4. Finalize Result
    if let Some((path, stats)) = last_result {
        if forward_dir {
            // Last pass was Forward (s1 -> s2). Return as is.
            Ok((path, stats))
        } else {
            // Last pass was Backward (s2 -> s1). Invert trajectory to match s1 -> s2.
            invert_path_trajectory(model, &seq_vec, &pt_start, &path)
        }
    } else {
        Err("Search loop finished without producing a result.".to_string())
    }
}



// --- Worker Function ---

/// Runs a single, direction-agnostic beam search pass.
fn run_beam_pass(
    model: &ViennaRNA,
    seq_vec: &NucleotideVec,
    start_pt: &PairTable,   
    initial_moves: &[Move], 
    m: usize,
    max_energy: Option<f64>,
) -> Result<(Vec<PathStep>, PathStats), String> {

    let total_steps = initial_moves.len();
    let start_energy = model.energy_of_structure(seq_vec, start_pt) as f64 / 100.0;

    // Check if the start structure already violates max_energy
    if let Some(max_e) = max_energy {
        if start_energy > max_e {
            return Err(format!("Start energy {:.2} already exceeds max_energy {:.2}", start_energy, max_e));
        }
    }

    let mut beam = vec![Intermediate {
        pt: start_pt.clone(),
        saddle_energy: start_energy,
        current_energy: start_energy,
        remaining_moves: initial_moves.to_vec(), 
        path: Vec::new(),
    }];

    for _step in 1..=total_steps {
        let mut next_candidates = Vec::new();

        // Expand all survivors in the beam
        for parent in beam {
            let mut neighbors = apply_move(model, seq_vec, &parent, max_energy);
            next_candidates.append(&mut neighbors);
        }

        if next_candidates.is_empty() {
             return Err("empty-warning. Search stuck (dead end due to topology or energy constraint)".to_string());
        }

        // Sort: Min Saddle -> Min Current
        next_candidates.sort_by(|a, b| {
            a.saddle_energy.partial_cmp(&b.saddle_energy).unwrap_or(Ordering::Equal)
                .then_with(|| a.current_energy.partial_cmp(&b.current_energy).unwrap_or(Ordering::Equal))
        });

        // Prune to keep only top 'm' candidates
        if next_candidates.len() > m {
            next_candidates.truncate(m);
        }

        beam = next_candidates;
    }

    // Select the absolute best winner
    let winner = beam.first().ok_or("No survivors in beam")?;
    
    // Reconstruct full trajectory history
    reconstruct_path_from_moves(model, seq_vec, start_pt, &winner.path)
}

// --- Helpers ---

/// Reconstructs the full Vec<PathStep> trajectory from a sequence of moves.
fn reconstruct_path_from_moves(
    model: &ViennaRNA,
    seq_vec: &NucleotideVec,
    start_pt: &PairTable,
    moves: &[Move],
) -> Result<(Vec<PathStep>, PathStats), String> {
    
    let mut trajectory = Vec::with_capacity(moves.len() + 1);
    let mut pt = start_pt.clone();
    let start_en = model.energy_of_structure(seq_vec, &pt) as f64 / 100.0;

    trajectory.push(PathStep {
        structure: DotBracketVec::try_from(&pt).unwrap().to_string(), 
        move_applied: None,
        energy: start_en,
        step_index: 0,
    });

    let mut saddle = start_en;

    for (i, mv) in moves.iter().enumerate() {
        // Apply move logic
        if mv.is_insertion {
            pt[mv.i] = Some(mv.j);
            pt[mv.j] = Some(mv.i);
        } else {
            pt[mv.i] = None;
            pt[mv.j] = None;
        }

        // Calculate and track energy
        let en = model.energy_of_structure(seq_vec, &pt) as f64 / 100.0;
        if en > saddle { saddle = en; }

        trajectory.push(PathStep {
            structure: DotBracketVec::try_from(&pt).unwrap().to_string(), 
            move_applied: Some(mv.clone()),
            energy: en,
            step_index: i + 1,
        });
    }

    let stats = PathStats {
        saddle_energy: saddle,
        barrier_energy: saddle - start_en,
        start_energy: start_en,
        end_energy: trajectory.last().unwrap().energy,
    };

    Ok((trajectory, stats))
}

/// Takes a backward trajectory (s2 -> s1), extracts the moves, reverses and inverts them, 
/// and reconstructs the forward trajectory (s1 -> s2).
fn invert_path_trajectory(
    model: &ViennaRNA,
    seq_vec: &NucleotideVec,
    true_start_pt: &PairTable,
    wrong_dir_path: &[PathStep],
) -> Result<(Vec<PathStep>, PathStats), String> {
    
    // Extract moves (skipping the step 0 start state)
    let moves: Vec<Move> = wrong_dir_path.iter()
        .skip(1) 
        .filter_map(|step| step.move_applied.clone())
        .collect();

    // Reverse the order and invert the insertion/deletion logic
    let inverted_moves: Vec<Move> = moves.iter().rev().map(|m| Move {
        i: m.i, 
        j: m.j, 
        is_insertion: !m.is_insertion
    }).collect();

    // Reconstruct the proper trajectory starting from S1
    reconstruct_path_from_moves(model, seq_vec, true_start_pt, &inverted_moves)
}



mod tests {
    use super::*;

    #[test]
    fn test_findpath_basic() {
        let model = ViennaRNA::default();
        let sequence = "AGCCAUGAGUGUAUAGUGGGCCUAU"; // short.txt from test_data
        let s1 = ".(((..............)))...."; 
        let s2 = "..((((.........))))......"; 

        let result = findpath(&model, sequence, s1, s2, 1, None);
        assert!(result.is_ok(), "Expected a valid path, got error: {:?}", result.err());
        
        let (path, stats) = result.unwrap();
        assert_eq!(path.len(), 8); // 
        assert_eq!(stats.start_energy, -2.2);
        assert_eq!(stats.saddle_energy, 4.3);
        println!("Test steps:");
        
        for step in path {
            println!("{} \t {} \t {}", step.structure,step.move_applied.unwrap_or_default(), step.energy );
        } 
        println!("Stats: {:?}", stats);
    }
}